# -*- coding: utf-8 -*-
"""iris_app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1utoDaZbc3XowbK0FYW3m-wYh1dWo1od4
"""

import streamlit as st
import numpy as np
import joblib

st.markdown('## iriis species prediction')
sepal_length=st.number_input('sepal length (cm)')
sepal_width=st.number_input('sepal width (cm)')
petal_length=st.number_input('petal length (cm)')
petal_width=st.number_input('petal width(cm)')

if st.button('predict'):
   model=joblib.load('iris_model.pkl')
   X=np.array([sepal_length,sepal_width,petal_length,petal_width])
   if any(X<=0):
      st.markdown('##input must be greater than 0')
   else:
      st.markdown(f'## prediction is {model.predict([[sepal_length,sepal_width,petal_length,petal_width]])[0]}')